# specify the node base image with your desired version node:<version>
FROM nikolaik/python-nodejs:latest

#SPECIFY WORKDIR BEFORE ANYTHING!!!!!!!!!!!! THERE IS A PROBLEM FROM NODE:16 IF YO
#DON'T DO THIS
#USER pn
WORKDIR /home/pn/app


#COPY FILES
COPY . /home/pn/app

#PIP INSTALL
# PANDAS DEVE ESSERE QUESTA VERSIONE!!!
RUN pip install pandas==1.5.3
#RUN pip install collections
RUN pip install numpy
RUN pip install nltk
RUN pip install scikit-learn
RUN python -c "import nltk;nltk.download('stopwords');nltk.download('punkt');nltk.download('wordnet');nltk.download('omw-1.4')"

# INSTALL SEPA CLIENT API
#RUN npm i @arces-wot/sepa-js #already installed locally, test if it works anyways

# replace this with your application's default port
EXPOSE 80
EXPOSE 443




#RUN node main.js